docker_common: &docker_common
  image: plugins/docker
  repo: metwork/drone-downstream-specific-image
  secrets: [ docker_username, docker_password ]

pipeline:
  docker_master:
    <<: *docker_common
    tags: 
      - latest
      - master
    when:
      branch: master
      event: push
  docker:
    <<: *docker_common
    tags: ${DRONE_BRANCH}
    when:
      branch: [ integration, pci_* ]
      event: push

branches: [ master, integration, pci_* ]
